[package]
name = "beef_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = { version = "0", features = ["native-tls"] }
tungstenite = "0.26.2"
